import streamlit as st
from langchain_core.messages import HumanMessage, AIMessage
from PyPDF2 import PdfReader
from graph_engine import medical_app

st.set_page_config(page_title="Multi-Agent Medical AI", layout="wide")
st.title("🩺 Multi-Agent Diagnostic Assistant")

# Initialize Session State
if "messages" not in st.session_state:
    st.session_state.messages = []
    # Initial greeting
    st.session_state.messages.append(AIMessage(content="Hello! I am your AI medical assistant. Please describe your main health problem, symptoms, and how long you've had them."))

if "pdf_text" not in st.session_state:
    st.session_state.pdf_text = ""

# Sidebar for File Uploads (Step 4 & 5)
with st.sidebar:
    st.header("📂 Upload Medical Reports")
    uploaded_file = st.file_uploader("Upload Lab Report (PDF)", type=["pdf"])
    
    if uploaded_file is not None:
        if st.button("Process Document"):
            with st.spinner("Extracting text via OCR/PyPDF..."):
                pdf_reader = PdfReader(uploaded_file)
                text = ""
                for page in pdf_reader.pages:
                    text += page.extract_text()
                st.session_state.pdf_text = text
                st.success("Document processed successfully!")

# Display Chat History
for msg in st.session_state.messages:
    role = "user" if isinstance(msg, HumanMessage) else "assistant"
    with st.chat_message(role):
        st.write(msg.content)

# Handle User Input
if prompt := st.chat_input("Type your symptoms or answer the questions here..."):
    # Add user message to UI
    st.session_state.messages.append(HumanMessage(content=prompt))
    with st.chat_message("user"):
        st.write(prompt)

    # Run the Multi-Agent Graph Engine
    with st.spinner("AI Agents are analyzing..."):
        # Create the initial state payload
        state_input = {
            "messages": st.session_state.messages,
            "lab_report_text": st.session_state.pdf_text,
            "is_info_complete": False
        }
        
        # Invoke the LangGraph workflow
        result = medical_app.invoke(state_input)
        
        # Get the latest message generated by the graph
        latest_ai_message = result["messages"][-1]
        
        # Update session state and UI
        st.session_state.messages.append(latest_ai_message)
        with st.chat_message("assistant"):
            st.write(latest_ai_message.content)